name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: 2.3.2
  retrofit: 4.1.0
  json_annotation: 4.8.1
  dio: 5.4.1
  dor_gen:
    path: ../dor_gen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.4.8
  retrofit_generator: 8.1.0
  json_serializable: 6.7.1



flutter:
  uses-material-design: true
