name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: 2.5.0
  retrofit: 4.4.2
  json_annotation: 4.9.0
  dio: 5.8.0+1
  dor_gen:
    path: ../
  equatable: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.4.15
  retrofit_generator: 9.1.9
  json_serializable: 6.9.4



flutter:
  uses-material-design: true
